version: '3.8'
services:
  db:
    build:
      args:
        MESSAGE_DB_VERSION: ${MESSAGE_DB_VERSION:-1.3.0}
      context: .
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
