name: Build Image

on:
  push:
    branches:
      - main
#    tags:
#      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout source code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: johnbcodes/message-db:latest
          build-args:
            - MESSAGE_DB_VERSION=${{ github.ref_name }}
      -
        name: Push GitHub Container Registry
        shell: bash
        run: |
          docker tag johnbcodes/message-db ghcr.io/johnbcodes/message-db:${{ github.ref_name }}
          docker push ghcr.io/johnbcodes/message-db:${{ github.ref_name }}
      -
        name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: Latest Message DB Docker Image
