name: Build Image

on:
  push:
    branches:
      - main
#    tags:
#      - v*
env:
  #MESSAGEDB_VERSION: 1.2.6
  MESSAGEDB_VERSION: test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          tags: johnbcodes/message-db:latest
      -
        name: Push GitHub Container Registry
        shell: bash
        run: |
          docker tag johnbcodes/message-db ghcr.io/johnbcodes/message-db:${{ env.MESSAGEDB_VERSION }}
          docker push ghcr.io/johnbcodes/message-db:${{ env.MESSAGEDB_VERSION }}